polyaxon/polyaxon

docs/templates/quick_start.md
The indentation in the last step was off by one which resulted in the following.
=> Fix indentation in "getting started" docs

docs/mkdocs.yml
Fixed two typos in the doc's headers.
=> Fix typos in docs page headers

docs/templates/customization/notifications.md
Adding missing 's' in the yaml configurations.
=> Typo in docs for integrations descriptions

docs/templates/installation/deploy_polyaxon.md, docs/templates/polyaxon_cli/commands/config.md
This PR includes 2 commits, both responsible for an update to the official doc to reflect the current options http_port and ws_port for `polyaxon config set` during the initial configuration of the cli.
=> polyaxon_cli config doc options fixes

docs/mkdocs.yml
=> Fix spelling of "Commands" in Docs

polyaxon/polyaxon/config_settings/registry.py
@mouradmourafiq As discussed in the slack I tried to implement the idea to change private registry spec from a single string to 3 fields. This modification reflects the spec change in the chart, [ref](https://github.com/polyaxon/polyaxon-chart/pull/16). 
What do you think about this ?
PS: I did not manage to test this on my GCP cluster.
=> [WIP] Add support to private registry spec as a dict with 3 fields: host,user,password

docs/templates/installation/deploy_polyaxon.md
I didn't not manage to get a working deployment of Polyaxon without running the `minikube service` command. Also I had to enable RBAC for the experiments to build properly.
Partially related to issue #308.
=> Update instructions for deploying on minikube

docs/references/polyaxon-helm-reference.md
According to the values.yaml file it should be plural i.e `nodeSelectors` not `nodeSelector`
=> Fix spelling error in polyaxon-helm-reference.md

docs/configuration/replication-concurrency.md
As discussed, the eventMonitors should be set to 1. I will follow up with a PRs to update:
* Charts to always default to one
* Deployment validation to warn users about setting this value
=> Remove `eventMonitors` from recommended services to scale

docs/configuration/ssl.md
K8S config should refer to helm values not actual env vars.
A follow up PR with updated helm chart.
=> Fix Documentation

docs/references/polyaxonfile-yaml-specification/build.md
=> Fix typo in yaml reference

docs/configuration/ssl.md
This seemed to be the culprit for issues with experiment groups grinding to a halt if too many were being run at the same time. I found this note in a comment in the Helm values when looking for something to increase the log level.
=> Add GKE note to documentation

docs/references/polyaxonfile-yaml-specification/declarations.md
Otherwise this would error with:
```
Polyaxonfile is not valid.
Error message `'batch' is undefined`.
```
=> Fix typo in declarations.md

docs/concepts/quick-start-external-repo.md
Two little fixes in the quick-start doc for external repos:
- Use the `project` command to check on the experiments
- Use `tensorflow/tensorflow:1.4.1-py3`, since there's no `tensorflow/tensorflow:1.4.1-py3sd` on Docker hub (typo?)
=> Fixes to quick start doc

polyaxon/scheduler/spawners/tensorboard_spawner.py
When launching a TensorBoard on a Polyaxon deployment with S3 set up as the output store, I get the following error:
```
Traceback (most recent call last): File "/polyaxon/polyaxon/scheduler/tensorboard_scheduler.py", line 42, in start_tensorboard tolerations=tensorboard.tolerations) File "/polyaxon/polyaxon/scheduler/spawners/tensorboard_spawner.py", line 180, in start_tensorboard command_args = self.get_stores_secrets_command_args(stores_secrets=stores_secrets) File "/polyaxon/polyaxon/scheduler/spawners/tensorboard_spawner.py", line 134, in get_stores_secrets_command_args cls.STORE_SECRET_KEY_MOUNT_PATH.format('envs3'), IndexError: tuple index out of range
```
This is because this format string has 4 `{}`'s, but is only given two arguments. Double-`{}`'ing works as an escape, so later …
=> Fix TensorBoards with S3 store

client/src/components/projects/projectAdd.tsx, docs/concepts/tensorboards.md
The "official" spelling seams to be TensorBoard: https://www.tensorflow.org/tensorboard
This changes the UI elements to adhere to that.
=> Fix spelling tensorboard --> TensorBoard

docs/configuration/custom-node-scheduling.md
`dockrer-registry` --> `docker-registry`
=> Fix docker-registry typo in docs

docs/integrations/gcr.md
This replaces `json_key` with `_json_key` which was required for me to follow this tutorial.
=> Docs: Fix typo in GCR auth file

docs/configuration/rabbitmq-ha.md
=> Fix typo in RabbitMQ config docs.

docs/setup/kubernetes.md
When issuing the deploy command, I received this error message:
The command `polyaxon deploy [-f]` is deprecated, please use `polyaxon admin deploy [-f]`.
I'm unsure how this change ought to be handled for different versions, I just want to raise visibility to this setup change.
Thanks for these great docs!
=> Update deploy command based on cli feedback

docs/resources/migration.md
I found out that teardown also removed pvcs that were created at install time. Luckily I had backups so nothing of value was lost, but it took me some time to figure out how to replay my db dump [1]. Also I had to reinstall 0.4.4 and redo the migration to make it work.
I hope the additional instructions will help someone to avoid this hassle :)
[1] https://serverfault.com/questions/984556/restore-sql-dump-in-a-running-kubernetes-deployment
PS: This is a PR because I didn't want to just complain without suggesting a improvement. Feel free to do it completely different.
=> Add some explanation to the migration instructions

.travis.yml
1307b86ee7a77e6aac1fcfc4cfe54263c9e3bd4b added some merge commit markers, that should be removed.
=> Remove merge conflict markers in travis.yml

docs/references/polyaxon-api/job.md, docs/references/polyaxon-api/project.md
Fixed typo pot -> post, api-post -> api-get and delete extra `json`.
=> Fix some typo in api docs

docs/setup/kubernetes.md
With Helm 3 there is no `--name` flag, the release name is passed as an unnamed argument.
=> Update Helm installation instructions for helm 3

docs/references/polyaxonfile-yaml-specification.md, docs/references/polyaxonfile-yaml-specification/build.md, docs/references/polyaxonfile-yaml-specification/environment.md
fix some typos in polyaxonfile yaml specification: 
1. Overview -> Tensorboard section, run: plugin -> run: tensorboard.
2. Build, Examples has replicated "Example using commit"
3. Environment, ps_resources -> ps
=> fix typo in polyaxonfile yaml specification

helm/platform/templates/sa.yaml
If RBAC is active, tensorboard and notebook are not starting due to:
```
"system:serviceaccount:polyaxon:polyaxon-polyaxon-serviceaccount\" cannot patch resource \"deployments\"
```
This is due extensions missing in serviceaccount chart.
=> [RBAC] extensions apiGroup is needed for tensorboard and notebook

dockerizer/README.md, docs/concepts/contributing.md, docs/concepts/introduction.md, helm/platform/README.md, platform/core/polyaxon/api/templates/polyaxon/footer.html
Old Slack invite link isn't working anymore. Substituted with the one from official polyaxon website.
=> Slack invite links outdated

core/polyaxon/client/transport/http_transport.py
Right now, the warning always shows 10.0MiB (i.e. the minimum size for showing the warning) instead of the actual file size. This commit should fix this.
=> Fix file size in upload size warning

core/polyaxon/cli/admin.py
Polyaxon v1 comes with sensible defaults for easy setup. However when calling `polyaxon admin deploy` or `polyaxon admin upgrade` without passing a config file it would fail with:
```python-traceback
$ polyaxon admin upgrade
Traceback (most recent call last):
File "/usr/local/bin/polyaxon", line 8, in <module>
sys.exit(cli())
File "/usr/local/lib/python3.7/site-packages/click/core.py", line 764, in __call__
return self.main(*args, **kwargs)
File "/usr/local/lib/python3.7/site-packages/click/core.py", line 717, in main
rv = self.invoke(ctx)
File "/usr/local/lib/python3.7/site-packages/click/core.py", line 1137, in invoke
return _process_result(sub_ctx.command.invoke(sub_ctx))
File "/usr/local/lib/python3.7/site-packages/click/core.py", line 1137, in invoke
return …
```
=> Fix polyaxon admin commands when calling without a config file

examples/in_cluster/horovod/keras/single-node-experiment.yml, examples/in_cluster/horovod/pytorch/single-node-experiment.yml, examples/in_cluster/horovod/tensorflow/single-node-experiment.yml
This PR contains three polyaxon files to run horovod-enabled experiments for keras, tensorflow and pytorch in a single node setup using multiple GPUs.
This is an alternative to running experiments as MPI jobs in the platform when users want to run an experiment on a single machine but exploiting more than one GPU.
I tested manually on a custom in cluster setup with nodes with more than one GPU available. I created a docker image with openMPI and the frameworks installed, similar to the Dockerfile available in the corresponding folders.
=> Add horovod single-node experiment polyaxon file examples for keras, tensorflow and pytorch

core/polyaxon/agents/base.py, core/polyaxon/cli/components/wait.py, core/polyaxon/logger.py, core/polyaxon/parser/parser.py, core/polyaxon/polyboard/processors/events_processors.py, core/polyaxon/tracking/contrib/fastai.py, core/polyaxon/tracking/contrib/keras.py, core/polyaxon/utils/cache.py, core/polyaxon/utils/encoding.py, core/polyaxon/utils/formatting.py, platform/polycommon/polycommon/apis/index/health.py
> A bare `except:` clause will catch `SystemExit` and `KeyboardInterrupt` exceptions, making it harder to interrupt a program with Control-C. (from https://www.flake8rules.com/rules/E722.html:)
I don't think this is desired in these cases so this PR replaces bare `except:` clauses with `except Exception:` which still catches all exceptions that signal program errors.
=> Do not rely on bare Python `except:`

core/polyaxon/tracking/contrib/keras.py
This PR simplifies the TensorFlow imports and instead uses the public TensorFlow API in favour of the private `tensorflow.python` imports.
=> Remove private TensorFlow API imports

core/polyaxon/connections/gcp/gcs.py
This PR fixes a bug when trying to delete directories containing empty files. The code on master failed since `size=0` is actually a valid size for a file or blob on GCS which would lead to GCS trying to delete a non-empty directory which fails.
This happens frequently when using the upload command with a Python codebase since there usually exists many empty `__init__.py` files.
This should fix #1273.
It would probably be good to add a test verifying this behaviour for the other storages backends as well. To be honest I am a bit surprised that this hasn't been caught before making me think I am missing something obvious, but I verified this manually and it seem to actually fix my issue.
=> GCS: Fix deletion of directories containing empty files

core/polyaxon/connections/gcp/gcs.py, core/tests/test_connections/test_gcp/test_gcs_store.py
This PR simplifies and improves the performance of deletion of GCS directories also working around issues like #1273.
In my testing deleting a 526.76 MiB directory of 277 objects over wifi with 5 workers sped up **8x** (from 39.8 s to 4.95 s wall time).
I only tested this manually, so I am not sure if I am missing some edge cases, but I checked that all objects have been removed.
=> GCS: Speedup deletion

core/polyaxon/connections/gcp/gcs.py, core/tests/test_connections/test_gcp/test_gcs_store.py
This PR is a follow up to #1275 and and removes the need to send two http requests when listing objects. This halves the GCS class A operations required and improves the speed of object listing by ~2x. I also removed the `blobs=True, prefixes=True` flags since they don't appear to be used and do not provide a performance benefit.
=> GCS: Speedup object listing

core/polyaxon/connections/gcp/gcs.py
This PR slightly improves the `download_dir` command by removing the need to make multiple `GET` bucket requests inside the threadpool.
Note that this PR is built ontop of #1277 so only the last commit is relevant for review. I'll keep it as a draft until #1277 is merged.
=> GCS: Slightly speedup `upload_dir`

core/requirements/requirements-dev.txt, core/setup.py, examples/tracking/sklearn/newsgroup/requirements.txt, examples/tracking/sklearn/random_forest/requirements.txt, examples/tracking/sklearn/sgd_classifier/requirements.txt, examples/tracking/xgboost/iris/requirements.txt
This PR upgrades the Polytune dependencies. In particular scikit-learn now ships with prebuilts wheels for Python 3.9 which should help install times (also on CI).
=> Upgrade Polytune requirements
