client/package.json

There doesn't exist `client/public/dist` directory in initial state of repo.

Fix setup npm

---

polyaxon/scheduler/spawners/experiment_spawner.py
polyaxon/scheduler/spawners/notebook_spawner.py
polyaxon/scheduler/spawners/templates/constants.py
polyaxon/scheduler/spawners/templates/volumes.py
tests/test_spawner/test_pod_volumes.py

Some references:
* https://stackoverflow.com/questions/46085748/define-size-for-dev-shm-on-container-engine/46434614#46434614
* https://github.com/kubernetes/kubernetes/issues/63126

Mount an tmpfs volume to /dev/shm to enlarge it

---

docs/templates/installation/deploy_polyaxon.md

Following discussions on slack, can propose an add on how to upgrade Polyaxon.
@mouradmourafiq feel free to comment out on how to modify it to make it better

Add how to upgrade Polyaxon section

---

docs/templates/quick_start.md

The polyaxon.yml file has been renamed polyaxonfile.yml and looks a bit different.

Fix minor errors with documentation in quick_start.md

---

polyaxon/polyaxon/config_settings/spawner.py

Available tf tags
https://hub.docker.com/r/tensorflow/tensorflow/tags?page=2

Update default tensorboard image to 1.12.0-py3

---

docs/configuration/custom-run-environment.md

I fixed the keys and values, since they were oppisite.

Fix documentation about custom TPU

---

docs/configuration/custom-run-environment.md

As discussed in Slack, this part lacked some information (at least for me). This should give some more hints to new users.

[Docs] Add more details and example for secrets

---

docs/references/polyaxonfile-yaml-specification/hptuning.md

This was not initially clear to me.

Update hptuning.md to clarify polyaxon_file type

---

docs/configuration/custom-data-storage.md

This fixes a couple of typos in the documentation.

Fix a few typos

---

docs/configuration/external-repos.md

In example yaml:
expiriment -> experiment

minor typo fix

---

docs/configuration/external-repos.md

apologies for running two CI builds for such a small typo.

second minor typo fix

---

docs/integrations/nginx.md

Add note about annotations in nginx ingress

---

README.md
client/src/components/experiments/experimentActions.tsx
client/src/components/groups/groupActions.tsx
polyaxon/api/templates/polyaxon/react_header.html

Just to be consistent. See #495

Replace Tensorboard --> TensorBoard

---

docs/resources/migration.md

Fix a link in migration.md

---

docs/integrations/acr.md
docs/integrations/dockerhub.md
docs/integrations/gcr.md

Modify typos in docs

---

docs/integrations/gcr.md

Describes adding secret key reference to polyaxon stores panel.

Updates gcr.md

---

docs/guides/best-practices-for-deploying-polyaxon.md

Following https://docs.polyaxon.com/configuration/custom-node-scheduling/#node-selectors

Update nodeSelectors -> nodeSelector

---

polyaxon/options/registry/k8s_resources.py

I just figured that out iteratively by trial and error while looking at the logs.
Another proposal would be catch the `marshmallow.exceptions.ValidationError` and pass it on to the user. But I'm not sure if its feasible and I would need some guidance with that.

Clarification about default resource configuration

---

docs/setup/microk8s.md

This is needed for helm to work properly

add the microk8s config to the local kube profile

---

core/polyaxon/polyflow/params/params.py

I found it when reading https://polyaxon.com/docs/core/specification/params/.

A small docstring fix

---

site/docs/setup/agent/index.md

Extensions are inconsistent throughout the documentation (yaml or yml).

Fix an inconsistency problems in setup of agent

---

examples/in_cluster/spacy/dispacy/Dockerfile
examples/in_cluster/spacy/dispacy/app.py
examples/in_cluster/spacy/dispacy/build.yaml
examples/in_cluster/spacy/dispacy/component.yaml
examples/in_cluster/spacy/train/Dockerfile
examples/in_cluster/spacy/train/build.yaml
examples/in_cluster/spacy/train/component.yaml
examples/in_cluster/spacy/train/model.py

Add examples for Spacy (displacy and training) components as per https://github.com/polyaxon/polyaxon/issues/782#issue-628394239
I have an example where it could be added as a hub component, but this feels more appropriate since there are different pipelines and dataset validation processes

added spacy examples

---

site/docs/setup/platform/index.md

Easy navigation and easy reading for others.

Fix broken url in docs

---

core/polyaxon/cli/operations.py
core/polyaxon/cli/registry.py
core/polyaxon/polyflow/matrix/tuner.py
core/polyaxon/polyflow/schedules/cron.py
core/polyaxon/polyflow/schedules/datetime.py
core/polyaxon/polyflow/schedules/interval.py
core/polyaxon/polytune/search_managers/hyperband/manager.py
core/polyaxon/schemas/fields/str_or_list.py
core/polyaxon/tracking/contrib/pytorch_lightning.py
core/polyaxon/tracking/contrib/scikit.py
core/polyaxon/tracking/contrib/tensorflow.py
core/tests/test_deploy/test_deployment.py
core/tests/test_schemas/test_types/test_connections.py

This PR removes a few unused imports that my `pyflakes` complained  about.

Remove unused Python imports

---

core/polyaxon/connections/gcp/gcs.py
core/tests/test_connections/test_gcp/test_gcs_store.py

This PR simplifies `download_dir` on GCS by removing the need to recursively iterate over directories during downloading. This helps to make proper use of the threadpool and in my testing with `workers=5` leads to a **5x** speedup when downloading nested directories.

GCS: Speedup `download_dir`

---

site/docs/setup/platform/enterprise-control-plane.md

typo had 'borker' instead of 'broker'
